-- =========================================================
-- 인테리어 소품 100종 (선실 방꾸미기, 사용자 제공 일러스트 10장 크롭)
-- =========================================================
insert into public.item_catalog (sku, name, description, category, subcategory, rarity, buy_price, sell_price, placeable, source_label, active) values
  ('interior_tea_cart', '티 카트', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_dresser_lamp', '램프 서랍장', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_ladder_shelf', '사다리 선반', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_mini_fridge', '미니 냉장고', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_plant_side_table', '화분 사이드테이블', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_hanging_planter', '매다는 화분', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_lighthouse_frame', '등대 액자', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_string_lights', '조명 가랜드', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_bunting_flags', '깃발 가랜드', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_corkboard', '코르크보드', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_whale_plush', '고래 인형', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_shell_pillow_set', '조개 쿠션 세트', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_telescope', '망원경', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_lantern', '랜턴', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_tea_tray', '티 트레이', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_record_player', '턴테이블', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_hammock_chair', '해먹 체어', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_fish_tank', '어항', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_ship_wheel_deco', '조타륜 장식', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_seagull_mobile', '갈매기 모빌', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_rocking_chair_wheel', '조타륜 흔들의자', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_striped_bench_sofa', '스트라이프 벤치소파', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_writing_desk', '라이팅 데스크', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_display_cabinet', '진열장', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_round_tea_table', '원형 티테이블', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_striped_ottoman', '스트라이프 오토만', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_wall_shelf_bell', '벽선반', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_porthole_window', '등대 현창', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_nightstand_lamp2', '램프 협탁', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_coat_hanger_stand', '모자 옷걸이', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_kids_bed', '아동 침대', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_flower_side_table', '꽃병 사이드테이블', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_loveseat_sofa', '2인 소파', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_striped_armchair', '스트라이프 안락의자', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_study_desk', '서재 책상', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_vanity_table', '화장대', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_bookshelf', '책장', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_floor_lamp', '스탠드 조명', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_trunk_chest', '트렁크 상자', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_wheel_clock', '조타륜 시계', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_bunk_bed', '2층 침대', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_wardrobe', '옷장', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_sailor_coat_hooks', '세일러 코트걸이', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_shoe_bench', '신발장 벤치', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_folding_screen', '파티션', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_flower_mirror', '플라워 거울', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_curtains', '커튼', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_oval_rug', '타원 러그', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_towel_rack', '수건걸이', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_laundry_basket', '빨래바구니', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_vanity_stool', '화장대 스툴', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_nightstand_clock', '시계 협탁', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_storage_bench', '수납 벤치', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_shoe_drawer_nightstand', '신발수납 협탁', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_umbrella_stand', '우산꽂이', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_standing_mirror', '전신거울', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_drawer_chest3', '서랍장', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_entryway_hooks', '현관 옷걸이', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_blue_screen', '블루 파티션', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_plant_stand_trio', '화분 진열대 세트', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_round_dining_table', '원형 다이닝 테이블', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_rattan_chair', '라탄 체어', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_sideboard', '사이드보드', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_lemonade_cart', '레모네이드 카트', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_rattan_armchair', '라탄 안락의자', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_desk_books', '서재 책상 세트', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_bookshelf2', '책장', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_kitchen_island', '아일랜드 식탁', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_office_chair', '사무 의자', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_china_cabinet', '그릇장', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_baby_crib', '아기 침대', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_storage_bench_kids', '아동 수납벤치', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_beanbag_chair', '빈백 의자', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_floor_cushion', '플로어 방석', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_dog_bed', '강아지 침대', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_rainbow_shelf', '레인보우 책장', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_cloud_shelf', '구름 선반', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_kids_storage_shelf', '아동 수납장', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_kids_desk', '아동 책상', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_recliner_chair', '리클라이너', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_chaise_lounge', '셰이즈 라운지', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_rocking_chair2', '흔들의자', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_loveseat2', '2인 소파', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_nesting_tables', '이중 사이드테이블', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_striped_stool', '스트라이프 스툴', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_shell_chair', '조개 체어', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_purple_armchair', '라벤더 안락의자', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_pouf_ottoman', '퍼프 오토만', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_console_table', '콘솔 테이블', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_storage_bench2', '앵커 수납벤치', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_canopy_bed', '캐노피 침대', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_cottage_bed', '코티지 침대', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_wardrobe_cane', '라탄도어 옷장', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_drawer_chest2', '9서랍장', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_kitchen_cart', '키친 카트', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_daybed_teddy', '테디베어 데이베드', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_display_cabinet2', '유리 진열장', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_ladder_shelf2', '사다리 선반', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_tv_console', 'TV 콘솔', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true),
  ('interior_secretary_desk', '세크리터리 책상', '인테리어 소품', 'furniture', 'interior_pack', 'common', 0, 2, true, '인테리어 컬렉션', true)
on conflict (sku) do nothing;


-- =========================================================
-- 인테리어 소품을 이미 생성된 모든 가족(household)의 가방(inventory_items)에 지급
-- 신규 가족은 onboarding/complete 라우트에서 동일하게 지급됨
-- =========================================================
insert into public.inventory_items (household_id, catalog_item_id, quantity)
select h.id, c.id, 1
from public.households h
cross join public.item_catalog c
where c.subcategory = 'interior_pack'
  and not exists (
    select 1 from public.inventory_items i
    where i.household_id = h.id and i.catalog_item_id = c.id
  );
