-- 한 벌 의상(전신 교체) 옷장 확장 — 이미 정규화되어 있었지만 상품으로 등록된 적 없던
-- outfit_full/dress_full 자산 46개(해녀 16 + 해녀 원피스 8 + 해남 항해사 7 + 해남 기관사 8 +
-- 새싹 7)와, design-assets/"기관사 항해사 해남이 의상 (2).png"(이번에 처음 발견한, 기존
-- outfit_full 20종과는 다른 신규 24벌 세트 — 기관사 12 + 항해사 12)를 크롭·정규화해 새로
-- 만든 자산을 item_catalog + store_products에 등록한다. 총 70개.
--
-- 기존 상의/하의/원피스/신발 분리 판매 데이터는 전혀 건드리지 않는다(요청사항) — 이 마이그레이션은
-- 순수 추가(insert)만 한다. on conflict do nothing으로 멱등 처리.

insert into public.item_catalog
  (sku, name, description, category, subcategory, rarity, buy_price, sell_price, placeable, source_label, active)
values
  ('haenyeo_outfit_sailor', '세일러 원피스', '세일러 원피스', 'outfit', 'haenyeo', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_floral', '플로럴 원피스', '플로럴 원피스', 'outfit', 'haenyeo', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_mint_cardigan', '민트 가디건룩', '민트 가디건룩', 'outfit', 'haenyeo', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_navy_skirt', '네이비 스커트룩', '네이비 스커트룩', 'outfit', 'haenyeo', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_flower_skirt', '플라워 스커트룩', '플라워 스커트룩', 'outfit', 'haenyeo', 'common', 11, 2, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_duck_raincoat', '덕키 레인코트', '덕키 레인코트', 'outfit', 'haenyeo', 'rare', 13, 3, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_pink_bear', '핑크 베어룩', '핑크 베어룩', 'outfit', 'haenyeo', 'common', 11, 2, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_autumn_coat', '가을 코트룩', '가을 코트룩', 'outfit', 'haenyeo', 'rare', 14, 3, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_navy_crossbag', '네이비 크로스백룩', '네이비 크로스백룩', 'outfit', 'haenyeo', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_scuba', '스쿠버 슈트', '스쿠버 슈트', 'outfit', 'haenyeo', 'rare', 13, 3, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_bear_check', '베어 체크팬츠룩', '베어 체크팬츠룩', 'outfit', 'haenyeo', 'common', 11, 2, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_resort_bikini', '리조트 비키니룩', '리조트 비키니룩', 'outfit', 'haenyeo', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_pink_bear_dress', '핑크 베어 원피스', '핑크 베어 원피스', 'outfit', 'haenyeo', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_denim_jacket_dress', '데님자켓 원피스', '데님자켓 원피스', 'outfit', 'haenyeo', 'rare', 13, 3, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_apron', '가든 에이프런룩', '가든 에이프런룩', 'outfit', 'haenyeo', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenyeo_outfit_pink_coat', '핑크 코트룩', '핑크 코트룩', 'outfit', 'haenyeo', 'rare', 14, 3, false, '해기사 의상 팩', true),
  ('haenyeo_dress_sailor_mini', '세일러 미니원피스', '세일러 미니원피스', 'outfit', 'haenyeo', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenyeo_dress_coral_cardigan', '코랄 가디건 원피스', '코랄 가디건 원피스', 'outfit', 'haenyeo', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenyeo_dress_lavender_shirt', '라벤더 셔츠원피스', '라벤더 셔츠원피스', 'outfit', 'haenyeo', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenyeo_dress_coral_slip', '코랄 슬립원피스', '코랄 슬립원피스', 'outfit', 'haenyeo', 'rare', 13, 3, false, '해기사 의상 팩', true),
  ('haenyeo_dress_yellow_check', '옐로우 체크원피스', '옐로우 체크원피스', 'outfit', 'haenyeo', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenyeo_dress_white_lace', '화이트 레이스원피스', '화이트 레이스원피스', 'outfit', 'haenyeo', 'rare', 14, 3, false, '해기사 의상 팩', true),
  ('haenyeo_dress_beige_dot', '베이지 도트원피스', '베이지 도트원피스', 'outfit', 'haenyeo', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenyeo_dress_coral_shirt', '코랄 셔츠원피스', '코랄 셔츠원피스', 'outfit', 'haenyeo', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_shirt_white', '반팔 셔츠', '반팔 셔츠', 'outfit', 'haenam_deck', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_knit_sweater', '니트 스웨터', '니트 스웨터', 'outfit', 'haenam_deck', 'common', 11, 2, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_denim_jacket', '데님 자켓', '데님 자켓', 'outfit', 'haenam_deck', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_tee_shorts', '반팔 & 반바지', '반팔 & 반바지', 'outfit', 'haenam_deck', 'common', 9, 2, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_hoodie_jogger', '후드티 & 조거팬츠', '후드티 & 조거팬츠', 'outfit', 'haenam_deck', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_overfit_shirt', '오버핏 셔츠', '오버핏 셔츠', 'outfit', 'haenam_deck', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_homewear', '홈웨어', '홈웨어', 'outfit', 'haenam_deck', 'common', 9, 2, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_captain', '선장 정복', '선장 정복', 'outfit', 'haenam_deck', 'rare', 16, 4, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_uniform_map', '항해사 근무복', '항해사 근무복', 'outfit', 'haenam_deck', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_sweater_camera', '니트 스웨터룩', '니트 스웨터룩', 'outfit', 'haenam_deck', 'common', 11, 2, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_sunglasses_casual', '선글라스 캐주얼', '선글라스 캐주얼', 'outfit', 'haenam_deck', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_yellow_raincoat', '옐로우 우비', '옐로우 우비', 'outfit', 'haenam_deck', 'rare', 13, 3, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_red_safety_vest', '레드 세이프티 재킷', '레드 세이프티 재킷', 'outfit', 'haenam_deck', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_ocean_hoodie', '오션 후드', '오션 후드', 'outfit', 'haenam_deck', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_hoodie_crossbag', '후드 & 크로스백', '후드 & 크로스백', 'outfit', 'haenam_deck', 'common', 11, 2, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_trench_coffee', '트렌치코트 캐리어룩', '트렌치코트 캐리어룩', 'outfit', 'haenam_deck', 'rare', 15, 3, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_hawaiian_shirt', '하와이안 셔츠', '하와이안 셔츠', 'outfit', 'haenam_deck', 'common', 11, 2, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_dolphin_pajama', '돌고래 잠옷', '돌고래 잠옷', 'outfit', 'haenam_deck', 'rare', 13, 3, false, '해기사 의상 팩', true),
  ('haenam_deck_outfit_scarf_coat', '머플러 코트', '머플러 코트', 'outfit', 'haenam_deck', 'rare', 14, 3, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_tee_navy', '반팔 티셔츠', '반팔 티셔츠', 'outfit', 'haenam_engine', 'common', 9, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_tee_workpants', '반팔 셔츠 작업복', '반팔 셔츠 작업복', 'outfit', 'haenam_engine', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_hoodie_casual', '후드티 캐주얼', '후드티 캐주얼', 'outfit', 'haenam_engine', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_overalls_denim', '멜빵바지', '멜빵바지', 'outfit', 'haenam_engine', 'common', 11, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_sweatshirt', '맨투맨', '맨투맨', 'outfit', 'haenam_engine', 'common', 9, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_sport', '운동복', '운동복', 'outfit', 'haenam_engine', 'common', 9, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_pajama_check', '체크 잠옷', '체크 잠옷', 'outfit', 'haenam_engine', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_winter_padding', '겨울 패딩룩', '겨울 패딩룩', 'outfit', 'haenam_engine', 'rare', 15, 3, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_safety_orange', '세이프티 작업복', '세이프티 작업복', 'outfit', 'haenam_engine', 'common', 11, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_toolbelt', '공구벨트 작업복', '공구벨트 작업복', 'outfit', 'haenam_engine', 'common', 11, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_towel_gloves', '수건 작업복', '수건 작업복', 'outfit', 'haenam_engine', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_mug_casual', '머그컵 캐주얼', '머그컵 캐주얼', 'outfit', 'haenam_engine', 'common', 9, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_headphones_hoodie', '헤드폰 후드', '헤드폰 후드', 'outfit', 'haenam_engine', 'common', 11, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_engineroom_hoodie', '엔진룸 후드', '엔진룸 후드', 'outfit', 'haenam_engine', 'common', 11, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_tank_wrench', '탱크톱 & 렌치', '탱크톱 & 렌치', 'outfit', 'haenam_engine', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_tablet_shirt', '태블릿 워크셔츠', '태블릿 워크셔츠', 'outfit', 'haenam_engine', 'common', 10, 2, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_snorkel_tank', '스노클링 탱크톱', '스노클링 탱크톱', 'outfit', 'haenam_engine', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_long_padding', '롱패딩', '롱패딩', 'outfit', 'haenam_engine', 'rare', 15, 3, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_cloud_pajama', '구름무늬 잠옷', '구름무늬 잠옷', 'outfit', 'haenam_engine', 'rare', 13, 3, false, '해기사 의상 팩', true),
  ('haenam_engine_outfit_overalls_skewer', '멜빵 오버롤', '멜빵 오버롤', 'outfit', 'haenam_engine', 'common', 12, 3, false, '해기사 의상 팩', true),
  ('child_outfit_cream_romper', '크림 롬퍼', '크림 롬퍼', 'outfit', 'child', 'common', 8, 2, false, '해기사 의상 팩', true),
  ('child_outfit_blue_shirt_bag', '블루 셔츠룩', '블루 셔츠룩', 'outfit', 'child', 'common', 8, 2, false, '해기사 의상 팩', true),
  ('child_outfit_white_green_set', '화이트그린 세트', '화이트그린 세트', 'outfit', 'child', 'common', 8, 2, false, '해기사 의상 팩', true),
  ('child_outfit_stripe_set', '스트라이프 세트', '스트라이프 세트', 'outfit', 'child', 'common', 8, 2, false, '해기사 의상 팩', true),
  ('child_outfit_yellow_raincoat', '옐로우 우비', '옐로우 우비', 'outfit', 'child', 'rare', 10, 2, false, '해기사 의상 팩', true),
  ('child_outfit_blue_pajama', '블루 파자마', '블루 파자마', 'outfit', 'child', 'common', 8, 2, false, '해기사 의상 팩', true),
  ('child_outfit_winter_coat_scarf', '겨울 코트룩', '겨울 코트룩', 'outfit', 'child', 'rare', 10, 2, false, '해기사 의상 팩', true);
on conflict (sku) do nothing;

-- 옷가게(store_products)에 연결 — 0009_clothing_store.sql과 동일한 패턴(카테고리+서브카테고리
-- 매칭 자동 연결, not exists로 중복 방지). 이번엔 방금 넣은 SKU만 콕 집어서 넣는다(과거처럼
-- 카테고리 전체를 다시 스캔하면 이미 다른 목적으로 비활성화된 상품까지 실수로 다시 살아날
-- 위험이 있어 피한다).
insert into public.store_products (store_id, catalog_item_id, sort_order, active)
select
  (select id from public.stores where slug = 'clothing'),
  ic.id,
  1000 + row_number() over (order by ic.subcategory, ic.buy_price desc),
  true
from public.item_catalog ic
where ic.sku in (
  'haenyeo_outfit_sailor',
  'haenyeo_outfit_floral',
  'haenyeo_outfit_mint_cardigan',
  'haenyeo_outfit_navy_skirt',
  'haenyeo_outfit_flower_skirt',
  'haenyeo_outfit_duck_raincoat',
  'haenyeo_outfit_pink_bear',
  'haenyeo_outfit_autumn_coat',
  'haenyeo_outfit_navy_crossbag',
  'haenyeo_outfit_scuba',
  'haenyeo_outfit_bear_check',
  'haenyeo_outfit_resort_bikini',
  'haenyeo_outfit_pink_bear_dress',
  'haenyeo_outfit_denim_jacket_dress',
  'haenyeo_outfit_apron',
  'haenyeo_outfit_pink_coat',
  'haenyeo_dress_sailor_mini',
  'haenyeo_dress_coral_cardigan',
  'haenyeo_dress_lavender_shirt',
  'haenyeo_dress_coral_slip',
  'haenyeo_dress_yellow_check',
  'haenyeo_dress_white_lace',
  'haenyeo_dress_beige_dot',
  'haenyeo_dress_coral_shirt',
  'haenam_deck_outfit_shirt_white',
  'haenam_deck_outfit_knit_sweater',
  'haenam_deck_outfit_denim_jacket',
  'haenam_deck_outfit_tee_shorts',
  'haenam_deck_outfit_hoodie_jogger',
  'haenam_deck_outfit_overfit_shirt',
  'haenam_deck_outfit_homewear',
  'haenam_deck_outfit_captain',
  'haenam_deck_outfit_uniform_map',
  'haenam_deck_outfit_sweater_camera',
  'haenam_deck_outfit_sunglasses_casual',
  'haenam_deck_outfit_yellow_raincoat',
  'haenam_deck_outfit_red_safety_vest',
  'haenam_deck_outfit_ocean_hoodie',
  'haenam_deck_outfit_hoodie_crossbag',
  'haenam_deck_outfit_trench_coffee',
  'haenam_deck_outfit_hawaiian_shirt',
  'haenam_deck_outfit_dolphin_pajama',
  'haenam_deck_outfit_scarf_coat',
  'haenam_engine_outfit_tee_navy',
  'haenam_engine_outfit_tee_workpants',
  'haenam_engine_outfit_hoodie_casual',
  'haenam_engine_outfit_overalls_denim',
  'haenam_engine_outfit_sweatshirt',
  'haenam_engine_outfit_sport',
  'haenam_engine_outfit_pajama_check',
  'haenam_engine_outfit_winter_padding',
  'haenam_engine_outfit_safety_orange',
  'haenam_engine_outfit_toolbelt',
  'haenam_engine_outfit_towel_gloves',
  'haenam_engine_outfit_mug_casual',
  'haenam_engine_outfit_headphones_hoodie',
  'haenam_engine_outfit_engineroom_hoodie',
  'haenam_engine_outfit_tank_wrench',
  'haenam_engine_outfit_tablet_shirt',
  'haenam_engine_outfit_snorkel_tank',
  'haenam_engine_outfit_long_padding',
  'haenam_engine_outfit_cloud_pajama',
  'haenam_engine_outfit_overalls_skewer',
  'child_outfit_cream_romper',
  'child_outfit_blue_shirt_bag',
  'child_outfit_white_green_set',
  'child_outfit_stripe_set',
  'child_outfit_yellow_raincoat',
  'child_outfit_blue_pajama',
  'child_outfit_winter_coat_scarf'
)
and not exists (
  select 1 from public.store_products sp
  where sp.store_id = (select id from public.stores where slug = 'clothing')
    and sp.catalog_item_id = ic.id
);
